import {
  Customer,
  NewCustomer,
  // UpdateCustomer,
  Markeeting,
  Tips,
  NewTip,
  UpdateInvoice,
  NewLead,
  Instructor,
  Staff,
  Leads,
  Tickets,
  Messages,
  Questions,
  Login,
  AdminCourses,
  CustomerIn,
  UserCourses,
  Lessons,
  NewLesson,
  FifthPage,
  SixthPage,
  SeventhPage,
  NewOrder,
  UpdateOrder,
  EmptyPage,
  Categories,
  NewCategory,
  Orders,
  Invoices,
  NewInstructor,
  // UpdateInstructor,
  NewStaff,
  // UpdateStaff,
  NewInvoice,
  NewCompaign,
  NewCourse,
  Question,
} from "../pages";
import { course } from "../static/menuIcons";

export const IndexRoutes = [
  // { path: "/", component: Login },
  { path: "adminCourses", component: AdminCourses },
  { path: "coustomerIn", component: CustomerIn },
  { path: "userCourses", component: UserCourses },
  { path: "fifthPage", component: FifthPage },
  { path: "sixthPage", component: SixthPage },
  { path: "SeventhPage", component: SeventhPage },
  { path: "orders", component: Orders },
  { path: "newOrder", component: NewOrder },
  { path: "updateOrder", component: UpdateOrder },
  { path: "categories", component: Categories },
  { path: "newCategory", component: NewCategory },
  { path: "lessons", component: Lessons },
  { path: "newLesson", component: NewLesson },

  { path: "customers", component: Customer },
  { path: "newCustomer", component: NewCustomer },
  // { path: "editCustomer", component: UpdateCustomer },

  { path: "instructor", component: Instructor },
  { path: "newInstructor", component: NewInstructor },
  // { path: "updateInstructor", component: UpdateInstructor },

  { path: "staff", component: Staff },
  { path: "newStaff", component: NewStaff },
  // { path: "updateStaff", component: UpdateStaff },

  { path: "invoices", component: Invoices },
  { path: "updateInvoice", component: UpdateInvoice },
  { path: "newInvoice", component: NewInvoice },

  { path: "tickets", component: Tickets },
  { path: "messages", component: Messages },
  { path: "questions", component: Questions },
  { path: "leads", component: Leads },
  { path: "newLead", component: NewLead },
  { path: "newCourse", component: NewCourse },

  { path: "markeeting", component: Markeeting },
  { path: "newCampaign", component: NewCompaign },

  { path: "tips", component: Tips },
  { path: "newTip", component: NewTip },
  { path: "question", component: Question },
  { path: "/", component: Lessons },

  // { path: "login", component: Login },
];